services:

  postgres:
      image: postgres:16
      container_name: postgres-db
      restart: always

      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin123
        POSTGRES_DB: authdb

      networks:
        - internal

      volumes:
        - postgres_data:/var/lib/postgresql/data/
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: redis-db
    restart: always
    networks:
      - internal
    volumes:
      - redis_data:/data


  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_REDIS_HOST: redis-db
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - internal

  data-service:
    build:
      context: ./data-service
      dockerfile: Dockerfile
    container_name: data-service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/datadb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_REDIS_HOST: redis-db
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - internal

volumes:
  postgres_data:
  redis_data:

networks:
  internal:
    internal: true